version: '3'

services:
  app:
    build: .
    container_name: blog-app2
    environment:
      - MONGO_URI=mongodb://db:27017/blog
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:latest
    container_name: blog-db2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
