FROM node:19

WORKDIR /app

RUN apt-get update \
    && apt-get install -y \
    libx11-xcb1 \
    libxrandr2 \
    libxcomposite1 \
    libxcursor1 \
    libxdamage1 \
    libxfixes3 \
    libxi6 \
    libgtk-3-0 \
    libatk1.0-0 \
    libasound2 \
    libdbus-1-3 \
    xvfb \
    curl \
    gnupg2 \
    ca-certificates \
    lsb-release \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

RUN npm install

RUN npx playwright install firefox --with-deps

COPY . .

CMD ["node", "app.js"]

